apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  ports:
  - port: 6379 # the port that this service should serve on
  selector:
    app: redis
    role: follower
    tier: backend
